package com.pg
// byte we can save memmory 8 bits only it use
byte b=10
println "$b"
println Byte.MIN_VALUE
println Byte.MAX_VALUE
// to print data type
println b.getClass().getName()
//type casting
def bd=(Integer)10
println bd.getClass().getName()
println "=============="
// short
short s=10
println "$s"
println Short.MIN_VALUE
println Short.MAX_VALUE
println "=============="
// int
int i=10
println "$i"
println Integer.MIN_VALUE
println Integer.MAX_VALUE
println "=============="
// long
long l=10
println "$l"
println Long.MIN_VALUE
println Long.MAX_VALUE
println "=============="
// float
float f=10
println "$f"
println Float.MIN_VALUE
println Float.MAX_VALUE
println "=============="
// double
double d=10
println "$d"
println Double.MIN_VALUE
println Double.MAX_VALUE
println "=============="
// char
// boolean
boolean falg=true
println "$falg"

println "=============="
// string