from tkinter import *
window = Tk()
window.title("Widget Examples")
window.minsize(width=500, height=500)
label=Label(text="just a labelgrid")
label.config(padx=100,pady=100)
label.grid(row=1,column=1)
button=Button(text="button1")
button.grid(row=2,column=2)
button2=Button(text="button2")
button2.grid(row=1,column=3)
entry = Entry(width=30)
entry.insert(END, string="Some text to begin with.")
entry.grid(row=4,column=4)
window.mainloop()
